In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.datasets import load_wine

In [ ]:
lw = load_wine()

In [ ]:
lw.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
df = pd.DataFrame(lw['data'], columns = lw['feature_names'])

In [ ]:
df['target'] = lw['target']

In [ ]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [ ]:
df.agg('mean std'.split()).transpose()

                                    mean         std
alcohol                        13.000618    0.811827
malic_acid                      2.336348    1.117146
ash                             2.366517    0.274344
alcalinity_of_ash              19.494944    3.339564
magnesium                      99.741573   14.282484
total_phenols                   2.295112    0.625851
flavanoids                      2.029270    0.998859
nonflavanoid_phenols            0.361854    0.124453
proanthocyanins                 1.590899    0.572359
color_intensity                 5.058090    2.318286
hue                             0.957449    0.228572
od280/od315_of_diluted_wines    2.611685    0.709990
proline                       746.893258  314.907474
target                          0.938202    0.775035

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
st = sc.fit_transform(df)

In [ ]:
df_st = pd.DataFrame(st)

In [ ]:
df_st.agg('mean std'.split()).transpose().astype(int)

    mean  std
0      0    1
1      0    1
2      0    1
3      0    1
4      0    1
5      0    1
6      0    1
7      0    1
8      0    1
9      0    1
10     0    1
11     0    1
12     0    1
13     0    1