In [ ]:
import pandas as pd
import numpy as np
!pip install efficient-apriori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting efficient-apriori
  Downloading efficient_apriori-2.0.3-py3-none-any.whl (14 kB)
Installing collected packages: efficient-apriori
Successfully installed efficient-apriori-2.0.3

In [ ]:
from efficient_apriori import apriori

In [ ]:
ppd=pd.read_csv("groceriesDataset.csv")

In [ ]:
ppd

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,17,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9831,1,cooking chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9832,10,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9833,4,semi-finished bread,bottled water,soda,bottled beer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9834,5,chicken,tropical fruit,other vegetables,vinegar,shopping bags,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd1=ppd.iloc[:,0:3]

In [ ]:
pd1

      Item(s)               Item 1               Item 2
0           4         citrus fruit  semi-finished bread
1           3       tropical fruit               yogurt
2           1           whole milk                  NaN
3           4            pip fruit               yogurt
4           4     other vegetables           whole milk
...       ...                  ...                  ...
9830       17              sausage              chicken
9831        1    cooking chocolate                  NaN
9832       10              chicken         citrus fruit
9833        4  semi-finished bread        bottled water
9834        5              chicken       tropical fruit

[9835 rows x 3 columns]

In [ ]:
pd1["Item 2"].unique()

array(['semi-finished bread', 'yogurt', nan, 'whole milk', 'butter',
       'UHT-milk', 'cereals', 'other vegetables', 'tropical fruit',
       'rolls/buns', 'sugar', 'pastry', 'cream cheese', 'root vegetables',
       'canned beer', 'soda', 'beverages', 'berries', 'grapes',
       'zwieback', 'bottled water', 'curd', 'brown bread', 'oil', 'beef',
       'coffee', 'newspapers', 'pip fruit', 'citrus fruit',
       'meat spreads', 'salt', 'onions', 'condensed milk', 'salty snack',
       'butter milk', 'hamburger meat', 'photo/film', 'sliced cheese',
       'misc. beverages', 'pork', 'fruit/vegetable juice',
       'whipped/sour cream', 'sausage', 'dessert', 'red/blush wine',
       'flour', 'Instant food products', 'frozen vegetables', 'ham',
       'popcorn', 'shopping bags', 'herbs', 'specialty cheese',
       'white wine', 'ice cream', 'soft cheese', 'bottled beer', 'candy',
       'chewing gum', 'specialty bar', 'female sanitary products', 'meat',
       'mustard', 'margarine', 'frozen meals',
       'packaged fruit/vegetables', 'white bread', 'chicken',
       'hard cheese', 'cake bar', 'canned fish', 'hygiene articles',
       'mayonnaise', 'specialty chocolate', 'domestic eggs',
       'frozen dessert', 'liquor', 'liver loaf', 'chocolate',
       'bathroom cleaner', 'pet care', 'honey', 'turkey', 'nut snack',
       'detergent', 'seasonal products', 'spread cheese',
       'long life bakery product', 'potted plants', 'dish cleaner',
       'processed cheese', 'spices', 'brandy', 'liquor (appetizer)',
       'fish', 'pickled vegetables', 'flower (seeds)', 'roll products',
       'napkins', 'organic sausage', 'dog food', 'pasta', 'rice',
       'finished products', 'vinegar', 'instant coffee', 'skin care',
       'softener', 'dental care', 'waffles', 'dishes', 'baking powder',
       'frozen potato products', 'jam', 'cream', 'sweet spreads',
       'cleaner', 'frozen fish', 'house keeping products',
       'canned vegetables', 'cat food', 'specialty fat', 'tidbits',
       'nuts/prunes', 'rum', 'male cosmetics', 'tea', 'organic products',
       'chocolate marshmallow', 'decalcifier', 'candles', 'canned fruit',
       'cookware', 'curd cheese', 'ketchup', 'cling film/bags', 'syrup',
       'artif. sweetener', 'prosecco', 'soups', 'light bulbs',
       'cocoa drinks', 'flower soil/fertilizer', 'sauces',
       'sparkling wine', 'salad dressing', 'soap', 'specialty vegetables',
       'snack products', 'kitchen towels', 'hair spray',
       'abrasive cleaner'], dtype=object)

In [ ]:
transactions=pd1.groupby(pd1['ITEM 0'])['food'].apply(lambda x:list(x))
transaction

AttributeError: ignored